shared:
  image: node:6

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - ayyyy:  echo -e "Hai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\nHai\nHello\nTesting\n"
      - exit: exit 1
      - do_not_run: printf "will not run"
      - teardown-lusol: printf bye
