shared:
  image: node:6

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - ayyyy: printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
                printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
                printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
                printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
               printf "goodbye"
      - hello: printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
               printf "hello world"
      - exit: exit 1
      - do_not_run: printf "will not run"
      - teardown-lusol: printf bye
