shared:
  image: node:6

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - ayyyy: |
        for i in {1..1000}
          do
             echo "Welcome $i times"
          done
      - exit: exit 1
      - do_not_run: printf "will not run"
      - teardown-lusol: printf bye
