shared:
  image: node:6

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - ayyyy: |
                cat ./ascii-art.txt
      - exit: exit 1
      - do_not_run: printf "will not run"
      - teardown-lusol: printf bye
